version: "3.9"
services:
  nginx:
    container_name: nginx
    build: .docker/nginx
    command: nginx -g "daemon off;"
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html:ro
    depends_on:
      - php
    networks:
      - check24-app-network

  php:
    container_name: php
    build: .docker/php
    links:
      - mysql
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    networks:
      - check24-app-network

  mysql:
    build: .docker/mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root-password'
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: 'password'
    ports:
      - "3306:3306"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
      - .docker/mysql/data:/var/lib/mysql
    networks:
      - check24-app-network

networks:
  check24-app-network:
    driver: bridge